# These environment variables must be set in Travis CI UI
#
# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
# DOCKER_USER - username for docker hub
# DOCKER_PASS - password for docker hub
#
language: python
cache: pip
services:
- docker

# build Docker image first to make sure it'll build correctly
before_install:
- bin/build
# run tests using an upgraded version of docker-compose
install:
- pip install --upgrade docker-compose
# run the tests using our test script
script:
- bin/test

# appropriately tag and push the container to dockerhub
after_success:
- bin/deploy

# notify atmo-dev channel
notifications:
  irc:
    channels:
    - ircs://irc.mozilla.org:6697#atmo-dev
    use_notice: true
    on_success: change
    on_failure: always
